### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by akshaypatil1** [smipi1/multibyr#1]
I'm using windows. It works fine me up-to uploading and replying response, then after on my cmd i got one error like below :

```
      D:\onetest>node server.js
      express deprecated app.configure: Check app.get('env') in an if statement server.js:22:5
       App listening on port 3033
      127.0.0.1 - - [Thu, 11 Sep 2014 07:37:41 GMT] "POST /api/pdf HTTP/1.1" 200 332 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.103 Safari/537.36"

    events.js:72
     throw er; // Unhandled 'error' event
          ^
      Error: ENOENT, open 'D:\dev\null'

 D:\onetest>
```

and server crashes. I'm not getting why.
my code is :

```
   app.post('/api/pdf', function (req, res) {

var multibyr = Multibyr({ dest: "pdf" });
     return multibyr.parse(req, res, function(err, files) {
      if(err) {
            multibyr.discard(files);
            return res.json(400, {err: err, files: files});
      }
         res.json(200, files);
      });
    });
```

UPDATE : my express version is 3.0.0

**Comment by smipi1** [comment]
To be honest, I never tried multibyr with Express 3. I developed it with Express 4, but that shouldn't matter.

Your problem however, does not seem to be related to multibyr. With such a limited stack-trace and very little source to go on, I cannot say for sure.

However:
Don't call the Multibyr() constructor within app.post(). You should construct it outside your post() handler or route() definition and use it within. Multibyr is almost middleware, so you should treat it in a similar manner. Don't construct a new instance every time the client hits a method.
